### ISSUE TITLE
Unable to stop entry once it's started

### ISSUE THREAD

**Issue by exhuma** [tobiaswaelde/vscode-clockify#50]
I started an entry using the command-palette (CTRL+Shift+P) then selecting `Clockify: Start Tracking`.

The entry is now running but I can't stop it. Neither via the command-palette, nor the status-bar button. In the output of VS-Code I see this:

```
2024-10-15 07:36:42.149 [error] [Extension Host] Error stopping time entry AxiosError: Request failed with status code 400
    at Pe (/home/node/.vscode-server/extensions/tobiaswaelde.clockify-tracker-4.0.3/dist/extension.js:2:405467)
    at IncomingMessage.<anonymous> (/home/node/.vscode-server/extensions/tobiaswaelde.clockify-tracker-4.0.3/dist/extension.js:2:417000)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by exhuma** [comment]
I just saw in the web UI that for some reason the entry had no project. Might have been a misclick when starting the issue.

In any case, it would be nicer to have a popup to select the project when the task is stopped and it has no project yet.
